### ISSUE TITLE
Game stil in progres

### ISSUE THREAD

**Issue by peleon02** [Cloxen/PUBG-Battlepoint-FarmBot#10]
Game stil in progres

**Comment by R1vALHimself** [comment]
Game still in progress !!!

**Comment by peleon02** [comment]
Sry I'm just retard and don't have time to write and I thought that it was ok. Thx for telling me

**Comment by R1vALHimself** [comment]
I have an idea !
Spam his email with messages to fix it 
mhowell35@student.cccs.edu

**Comment by peleon02** [comment]
I don't think that spamming is the fix to tell him to fix it, I know python I could try to fix it at home

**Comment by R1vALHimself** [comment]
fix it and post the code please

**Comment by Cloxen** [comment]
Please don't spam me. I don't have time to work on the bot anymore, but everyone is welcome to have a go at it

**Comment by peleon02** [comment]
Can you give me an email and in less than one week I send you fixed?, Also could you tell me the line of leave the game? (I mean number)

**Comment by Cloxen** [comment]
You want the line number in the code where I handle exiting the game ? Or are you looking for something else ? 

Also you can do a pull request here once you get it working

**Comment by peleon02** [comment]
Yes, to put to skip that msg after it. Also  could I add my name as the fixer of that?

**Comment by Cloxen** [comment]
Yeah that's cool. When I get on my computer later ill look through the lines and tell you

**Comment by peleon02** [comment]
Ok I finish it, 
https://mega.nz/#!WMljUKSZ!NofHy25iuN9JZlPv2Av58KCNnOR660vdgt0C0UcaAZM
I think that know should be V2.1
also change the jumping time, cuz some times in the new map u die into the water.
I also add my name into the gui telling that I fix that

**Comment by peleon02** [comment]
I forgot to add the program that you need to use to knwo the coords 
https://mega.nz/#!3J0zETaJ!l0933zlw9WiNkAiqW4DFWbbNuUAsjmYENWr67YOrnl4

**Comment by Cloxen** [comment]
It would be better if you do a pull request so I can check it against the current code and so you can get your proper credit. The changes will be tracked back to you that way as well

**Comment by peleon02** [comment]
I tried to do it and idk who, tomorrow I will look how does it work

**Comment by peleon02** [comment]
Don't wanna spam but I wrote who with my mobile and it's How ofc, srry

**Comment by R1vALHimself** [comment]
Make the bot leave the match after the player has been killed

**Comment by peleon02** [comment]
I´ve already done it and I´ve already done the pull request :)

**Comment by R1vALHimself** [comment]
Is the pull request the same as the mega link you posted

**Comment by peleon02** [comment]
No, the mega link  has a wrong function

**Comment by R1vALHimself** [comment]
Where can i download the other

**Comment by peleon02** [comment]
Is in the pull request, you can check my profile and there is the fork

**Comment by R1vALHimself** [comment]
How can i download it

**Comment by R1vALHimself** [comment]
nvm i found how to download it

**Comment by R1vALHimself** [comment]
they killed me and it didnt exit

**Comment by R1vALHimself** [comment]
should the input texts be like
+1021 626

+1721 960

**Comment by R1vALHimself** [comment]
the bot stops choosing the match after the first left

**Comment by R1vALHimself** [comment]
When i am killed it doesnt leave the match neither when match is still in progress

**Comment by peleon02** [comment]
The "+" doesn't have  to be there. It does leave the math at the time that it exit the game I mean, when the bot is going to leave the game click on the button to skip in case that you die, it leaves the game. This morning I left it 6 h and not even one error

**Comment by R1vALHimself** [comment]
should the input be like this 1021 6261721 960 or like this 1021 626
1721 960

**Comment by peleon02** [comment]
Like the second one 

first the cancel button 
Then the die button

**Comment by R1vALHimself** [comment]
![image](https://user-images.githubusercontent.com/32874703/35291242-68c301e6-0075-11e8-99da-789a1af71ded.png)
Mt default is like this

**Comment by peleon02** [comment]
Maybe because you are using a different text editor, but it shuold be like this 
![imagen](https://user-images.githubusercontent.com/8939077/35291390-6d9776aa-006d-11e8-95ca-d81350e5483f.png)

**Comment by R1vALHimself** [comment]
How much for 1 hour

**Comment by Cloxen** [comment]
Ill give the pull request a look over in the next few days(hopefully if I have enough time) and then I will accept it and add you to the contributors thanks!

**Comment by peleon02** [comment]
I dont know one hour. In a morning I took 3.8k

**Comment by codetyper** [comment]
We have a new problem.
"Servers are too busy":
https://ibb.co/ghmPtb

**Comment by peleon02** [comment]
Let me 10 m to fix it

**Comment by R1vALHimself** [comment]
![image](https://user-images.githubusercontent.com/32874703/35348138-d305255a-013f-11e8-9021-109296087bad.png)

**Comment by peleon02** [comment]
I'm taking the  bus xd I promise that In less than 3 hours I will release the 2.3 Beta2 and this Friday will be also an updater ♥️

**Comment by R1vALHimself** [comment]
no 2.3 how can i download it

**Comment by peleon02** [comment]
Ok, Pubg has made an update into the anti-cheat, IDK how safe could be use this now

https://mega.nz/#!SA9FEZja!QtojJwftT0oSIs36n9di45vgfTpqHI4gR11pB7-rmkU

**Comment by R1vALHimself** [comment]
Thank you for the update

**Comment by madDANET** [comment]
YEAH MAN, SAME ERROR FROM ALL VERSIONS..

"can't interact with game, control  denied"

**Comment by kuwarks2** [comment]
Hey peleon thanks for the updates man really appreciate it. Ive used it as much as 3 hours without any issues but lately it started getting stuck at "game still in progress" any idea how to add the coordinates for 1366x768? Because the bot just kills the game and itself when that pops up. And what happened to the friday update? Thanks in advance.

**Comment by peleon02** [comment]
I added to the instructions how to change the coords to different resolutions, if u need an app.to check it reply me back ♥️

**Comment by kuwarks2** [comment]
Found it. Its just changing it on input.txt right? If you can send an app plis do.

**Comment by kuwarks2** [comment]
Nvm I found the coordinates. The mouse only stays on the cancel button it doesn't click it what do? Also I saw your update on the mpgh board. The link gets censored btw. Would like to also get a copy of your farmbot.py

**Comment by peleon02** [comment]
The farmbot Py is here in this thread

**Comment by peleon02** [comment]
I would like if you can follow me or at least check my twitter @peleon02 , there I will answer questions better and also put the deadline to the 2.4V and some changes will be posted there

**Comment by maulwurfpy** [comment]
what coords do i have to add for 1366x768?

**Comment by verobin2237** [comment]
727 442

**Comment by peleon02** [comment]
There's to pair of coords

**Comment by verobin2237** [comment]
what's the other coordinate for and between it doesnt click the cancel :(

**Comment by peleon02** [comment]
First of all make sure to read the instructions of my fork on my github  to understand all, but it's for click the die one, so just suicide and take the coordinates of , leave to lobby in the bot corner

**Comment by verobin2237** [comment]
mouse pointer goes to the cancel button but it doesnt click the cancel button :(

**Comment by peleon02** [comment]
Have to write the code again in that case

**Comment by verobin2237** [comment]
have you tried it after finishing making the script?

**Comment by peleon02** [comment]
What do you mean?

**Comment by verobin2237** [comment]
Have you tried running the script on PUBG after finishing making the script?

**Comment by verobin2237** [comment]
did it work for you?

**Comment by peleon02** [comment]
Ofc

**Comment by verobin2237** [comment]
i think its working but it didnt work at the first time
...well i gues i dont have a problem anymore

**Comment by peleon02** [comment]
:)

**Comment by kuwarks2** [comment]
There's a new pubg update (#4) feat new anti cheat measures as well. Anyone know if this is still safe?

**Comment by peleon02** [comment]
@kuwarks2
The thing is that, this a script that click and press keys, and as I read yesterday , If the code isn't in the anticheat it shouldn't be bannable

**Comment by verobin2237** [comment]
ok now i am encountering a new prob and that is ...it stucks at the reconnect screen...the bot doesnt click or do anything unless i myself click on the RECONNECT button

**Comment by peleon02** [comment]
I don't know why and I can't test myself on that resolution. In my resolution at least six hours

**Comment by verobin2237** [comment]
ok the problem isnt gone...it doesnt click the Cancel button... :((((

but i did figure out something to bypass this easily....Can you add the keyboard button click "ESC" at the end.... Pressing the ESC button on keyboard also cancels out that Window

**Comment by Cloxen** [comment]
Ill look into it when i get some time, been busy

**Comment by verobin2237** [comment]
It would be great if you guys make tutorial video and just a video of how it's working

**Comment by peleon02** [comment]
I don't know if its for me but I tryed and I can't record and play at the same time

**Comment by verobin2237** [comment]
use an on screen recording software like OBS Studio...that would help too 
The edited version of Cloxen's script ...after using it i end up with only one same problem is that it doesnt click the cancel button even though the cursor does go to the cancel button position ....and sometimes it doesnt even click on the start match button aswell 
Where as with Cloxen's script it works perfectly except the canceling out the reconnect button thingy

**Comment by Cloxen** [comment]
So the issue you are having with my script is that it doesnt skip the reconnect prompt? @verobin2237

**Comment by verobin2237** [comment]
that is just one of two probs
1)doesnt skip or click the reconnect button when net is having a prob
2)going back to lobby after a match the games shows a small in-game window that says "Match in progress...reconnect?" the bot doesnt click or skip

**Comment by peleon02** [comment]
Here is the click reconnect fix https://twitter.com/peleon02/status/960867299279491073
and the thing that I think that I cant and Cloxen cant too, is the reconnect buttom (he could do it¿? IDK at least I cant) because You never know the times that it might be clicked

**Comment by verobin2237** [comment]
ok ,,,maybe this will fix it... anyways thnx for the help

**Comment by Cloxen** [comment]
Im pretty sure i can fix exiting the reconnect button, I think i still have old code in there that already fixes it just needs to be updated a little bit to work again

**Comment by Cloxen** [comment]
@peleon02 How has you version of the bot been going, I saw from a few other comments that it was having a few issues, is it stable now? 

I havent gotten to test yet since I have been busy and i dont have the game installed anymore

**Comment by verobin2237** [comment]
i think pubg gave a patch update which made bp farming abit slower

**Comment by Cloxen** [comment]
I stopped playing in sept so I honestly have no idea

**Comment by peleon02** [comment]
@Cloxen I think so

**Comment by verobin2237** [comment]
if only there was a way to get 100 million bp with script hack...... :3

**Comment by R1vALHimself** [comment]
1.Reconnect button
2.Servers busy 
3.Bot crashes after 1 hour 
4.It is a bit slow
5.Do you really need to wait so much to exit the game ? I think it gives you the bp points anyway
6.Too slow on exit game if you are killed 
7.Make the bot faster

**Comment by R1vALHimself** [comment]
These are all the issues

**Comment by R1vALHimself** [comment]
Also there is sometimes when the bot exits the game Are you sure you want to chicken out

**Comment by peleon02** [comment]
@R1vALHimself , I´m gonna tell you what can I (I, i dont know if cloxen can) do to all the "problems", The number 1 is right (I think, if you have a bad pc I´ve already given the fix) the number 2 fixed last version, at least one try to click if more I cant, bot crashes Don´t Know why, number 4 just bot when you cant play by yourself, it´s free BPs, 5 I don´t know that that is a @Cloxen thing and I think that´s right, 6- It exit at the same time that It will leave the game, at least that was my fix, could I make it with detect colors yes and no, because that color is shared with more and it could work really bad (IMO). 7- The same as 4, if you can play do it if you can´t, you can still getting BPs.

Is not flamming but You can consider learning to code in python (It´s funny) and you could make your own fixes, I understand you, but you Must undersand that I also use the bot and I try to make it work faster but I can´t, is just a bot, and PUBG keep updating things so the crash could be when it detects that you do the same lots of time¿? IDK, Just my opinion about all of that, I hope that my Versions can help anyone, I try my best doing it and I would like to let the bot run Perfect but PUBG updates make this slower and with crashes, We all know that this game isn´t optimiced right, and it has bugs, the bot too, so I update what I cant, and I´m sure that my mod, just add some clicks and the BPs that you earned the more than 95% of the whole code is made by @Cloxen and it´s a really nice code, stop telling problems, when we know and we cant fix it, I dont wanna be rude but I think what I told you. Have a nice botting :P

**Comment by R1vALHimself** [comment]
Another problem the bot clicks several times on the buttons

**Comment by peleon02** [comment]
I Know, thats the way to stop people saying that it doesnt click, make it click more than once, and where is the problem? I use the bot for 2 hours, no crashes

**Comment by R1vALHimself** [comment]
What is the BETA bot in the new version

**Comment by peleon02** [comment]
Small code fixes, that should work better

**Comment by R1vALHimself** [comment]
What would happen if the bot leaves right after it lands

**Comment by peleon02** [comment]
Nothing

**Comment by madDANET** [comment]
u get zero points

**Comment by R1vALHimself** [comment]
Should i use normal or beta version

**Comment by R1vALHimself** [comment]
and what is different in beta

**Comment by peleon02** [comment]
Now is the same

**Comment by peleon02** [comment]
Beta could have more bugs

**Comment by R1vALHimself** [comment]
it exits the game

**Comment by HashBrownClown** [comment]
Peleon02 thank you for your additions to the bot. Your versions seems to run a lot longer. Looking forward to future updates!

**Comment by R1vALHimself** [comment]
Why is the PC shutting down after 2 hours if you have 8 gb ram

**Comment by peleon02** [comment]
Beacause  Gb to pubg is LOW

**Comment by ehwjwisid** [comment]
1) it takes too much until i exit the game how can i change that?
2) If i lost internet connection i got stuck on do you want to continue your progressed match
3) Thanks for your hard work

**Comment by peleon02** [comment]
1. Is the minimun to take the coins
2. With my version is fixed lul 
XD

**Comment by ehwjwisid** [comment]
So i use your beta or main one?

**Comment by peleon02** [comment]
main one

**Comment by ehwjwisid** [comment]
1080 input bro?

**Comment by Cloxen** [comment]
What you said 20 days ago was pretty accurate peleon02. I think either ill add you on as an contributor for this repo or just redirect people to your fork since I do not think i will have time to come back to this project anytime soon. You should open the issues page on your repo so people can start issues there as well

**Comment by peleon02** [comment]
Opennened, and the pull reques is already there

**Comment by ClownApril** [comment]
It isn't working anymore right?

**Comment by peleon02** [comment]
which branch?

**Comment by Cloxen** [comment]
The pull request has been approved. If anyone has any further issues please post them in issue #22
