### ISSUE TITLE
Game crashing after a few games

### ISSUE THREAD

**Issue by Skyitzer** [Cloxen/PUBG-Battlepoint-FarmBot#11]
I've left the AFK bot running a few times when I'm away, and every time I get back, it's just on my desktop, with no game running. Might be an issue in the code with relaunching?

**Comment by codetyper** [comment]
Same here with version 2.0 & 2.1.

**Comment by peleon02** [comment]
Pls post details as OS and I will look at it

**Comment by codetyper** [comment]
Windows 10 x64.
Python 3.6.4 (64-bit)

Script works well, but sometimes crashes.
And we need to another new function. Bot doesn't exit to lobby after death if somebody kill us.

**Comment by peleon02** [comment]
I've already add that in the pull request, the crash I will look for it
