### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by madDANET** [Cloxen/PUBG-Battlepoint-FarmBot#13]
CAN'T INTERACT WITH GAME, ACCESS DENIED

**Comment by peleon02** [comment]
1st, don't use shitty names
2nd, have u got the game in full screen windowed?

**Comment by madDANET** [comment]
what is a shitty name iyo i don't know ... but anyways, im using fullscreen windowed, 1920x1080 in game, in windows resolution and reshade off.

**Comment by Cloxen** [comment]
If you have anything taking focus away from the pubg game window, then it will say that
