### ISSUE TITLE
Game Crashes after some hrs

### ISSUE THREAD

**Issue by maulwurfpy** [Cloxen/PUBG-Battlepoint-FarmBot#14]
Hey peleon
I still have the problem that the game and bot crashes after some time. The rest is running all fine but after some hrs everything is killed. No error message nothing and idk what happens

**Comment by peleon02** [comment]
Maybe GPU overcame

**Comment by maulwurfpy** [comment]
but then the computer should restart i think. I already checked the windows log file but nothing

**Comment by peleon02** [comment]
GPU, CPU, and SO please?

**Comment by maulwurfpy** [comment]
Everything seems normal

**Comment by Cloxen** [comment]
PUBG should have a crash log somewhere that tells you why it crashed
