### ISSUE TITLE
Possibility to read debug messages while in-game

### ISSUE THREAD

**Issue by f0nZ** [Cloxen/PUBG-Battlepoint-FarmBot#18]
Just wondering if you could implement with Tkinter a way to show what you print to cmd while in-game instead.

**Comment by peleon02** [comment]
I don't think that change is too important and it is to hard to do it so I don't think that's relevant

**Comment by Cloxen** [comment]
yea it wouldnt really be worth the hassle at this point, the only other way to see the issues is to run it from cmd and have the issues print to cmd which is how i use it to debug
