### ISSUE TITLE
Recent PUBG updates

### ISSUE THREAD

**Issue by bolpeensamp** [Cloxen/PUBG-Battlepoint-FarmBot#19]
With recent updates regarding the rewards system is this still viable?

**Comment by peleon02** [comment]
Yes, It still works

**Comment by nameuser15** [comment]
Powershall can't interact with game controls any fix?

**Comment by peleon02** [comment]
Did you try to run it as admin?

**Comment by nameuser15** [comment]
Yeah it just starts the game and says that controls denied

**Comment by gokhyildiz** [comment]
"Would you like to join the ongoing game?": when this screen comes out or when I open the bot after a certain period of time it throws away.

**Comment by Cloxen** [comment]
this issue is being solved in  #10
