### ISSUE TITLE
[updated bot] Merged peleon02's changes into the base branch

### ISSUE THREAD

**Issue by Cloxen** [Cloxen/PUBG-Battlepoint-FarmBot#22]
Let me or @peleon02 know of any issues you may have.

**Comment by R1vALHimself** [comment]
Bot only crashing

**Comment by Krissdrzp** [comment]
My bot is working a couple of hours, then it stops. How can i prevent that?

**Comment by peleon02** [comment]
Can you give more details with the "stop"?, and please try the beta version in my fork
and what do you mean with crashing?
Just pls put usefull things, so we can fix it, screenshot or more details

**Comment by Krissdrzp** [comment]
If i run the bot, i keep looking at it for a couple of rounds just to make sure it runs. After i come back, the game have been closed down and nothing happens.

**Comment by Cloxen** [comment]
sounds like it could be pubg crashing. what are the specs of your computer @Krissdrzp

**Comment by Krissdrzp** [comment]
My computer isn't the problem :s

Computer parts:
ASUS ROG Strix Z270H Gaming, Socket-1151
MSI GeForce GTX 1060 6GB OC
Cooler Master Hyper 212 LED Turbo
Corsair Vengeance LPX DDR4 2400MHz 16GB
Intel Core i5-6600 Skylake Prosessor
1 TB HDD (All programs)
150 GB SDD (Windows only)

**Comment by Cloxen** [comment]
yeah your specs are up to par. Does the pubg crash reporter tell you what the problem is ? 

Only thing I can think that would cause the game to crash is their new anticheat and buggy programing.
