### ISSUE TITLE
HDD dead

### ISSUE THREAD

**Issue by Aurhil** [Cloxen/PUBG-Battlepoint-FarmBot#23]
My hdd is dead the day after I have installed the bot, I don't know why and I don't know if it's because of the bot but I prefer to warn you.

**Comment by peleon02** [comment]
xDD, It cannot be the bot´s fault xddd

**Comment by Aurhil** [comment]
Ok but I don't understand why is it funny?

**Comment by peleon02** [comment]
Im not saying its funny, you just post that it could be the bot , come on xDD, I mean i dont wanna be rude but post that the bot kill your HDD idk xd

**Comment by Aurhil** [comment]
I said I don't know why my hdd is dead what do you want more? It's maybe a coincidence that's all. I prefer to warn other users if it's not a coincidence.
Think before answering contemptuously otherwise I do not know why you are there.

**Comment by peleon02** [comment]
Okey, I'm sorry but it's a coincidence

**Comment by Aurhil** [comment]
Thank you for your answer, have a good day.
