### ISSUE TITLE
Each match takes too long.

### ISSUE THREAD

**Issue by COMMANDERWONG** [Cloxen/PUBG-Battlepoint-FarmBot#25]
The minimum game time applicable for 60 BPs should be 4 mins per match,but the bot is taking 5 mins each.

**Comment by peleon02** [comment]
To make sure it works perfectly

**Comment by COMMANDERWONG** [comment]
Then could you please tell me how to change the match time,I will change it myself for maximum profit,thanks.

**Comment by Cloxen** [comment]
`timeout = time() + 315 - wait_for_plane`

reduce that by 60 seconds

**Comment by COMMANDERWONG** [comment]
Thank you.
