### ISSUE TITLE
bot not working whit new patch

### ISSUE THREAD

**Issue by electrifying** [Cloxen/PUBG-Battlepoint-FarmBot#27]
devs please fix this problem

**Comment by Cloxen** [comment]
What problemssare you having

**Comment by electrifying** [comment]
bot works through time, more often than not he writes
game controller is denaid

**Comment by Cloxen** [comment]
Can you give me a bit more clear detail on what you mean

**Comment by electrifying** [comment]
My character does not jump out of the plane, the bot selects the game connects and does not work any more. This happens too often.

**Comment by electrifying** [comment]
and bot not work

https://imgur.com/a/wC7Eb

**Comment by electrifying** [comment]
and add the option when the game is writing connection time out so that the bot presses ok

**Comment by Cloxen** [comment]
ill try to look into it soon, in the meantime lets keep all this in one issue #22
