### ISSUE TITLE
Bot not reconnecting correctly

### ISSUE THREAD

**Issue by andrekato1** [Cloxen/PUBG-Battlepoint-FarmBot#30]
On startup, sometimes you are asked to reconnect right away and it seems the bot can't handle this situation properly. If the game successfully launch, then there are no issues whatsoever.

**Comment by COMMANDERWONG** [comment]
I have the same issue too

**Comment by R1vALHimself** [comment]
me too

**Comment by peleon02** [comment]
I don´t know that this could happend, just try going to the line 199 press enter to make this the 200 and in the 199 put coordinadas()

**Comment by electrifying** [comment]
me too
