### ISSUE TITLE
Bot suddenly stopped.

### ISSUE THREAD

**Issue by COMMANDERWONG** [Cloxen/PUBG-Battlepoint-FarmBot#31]
My bot suddenly stopped and closed itself while farming,what's happened???

**Comment by peleon02** [comment]
try the beta version, and tell me <3

**Comment by COMMANDERWONG** [comment]
The beta doesn't work either.(Access denied)

**Comment by peleon02** [comment]
It's impossible

**Comment by COMMANDERWONG** [comment]
that worked,thanks
