### ISSUE TITLE
connection timeout whit bot working

### ISSUE THREAD

**Issue by electrifying** [Cloxen/PUBG-Battlepoint-FarmBot#32]
most often when the bot is turned on during the boot screen, the game will not turn on and an error will be displayed connection timeout 3.7.20 
when the bot does not work all is normal

**Comment by peleon02** [comment]
Can you take a screenshot of the error?

**Comment by electrifying** [comment]
https://imgur.com/6jFzm4R

**Comment by electrifying** [comment]
can't interact with game control denied DEVS FIX THIS

**Comment by peleon02** [comment]
DONT SHOUT, and if you don´t have the borderless or some shit need it don´t blame us, also I don´t know what a shitty timeout are you gettings, that´s not the bot´s fault
