### ISSUE TITLE
if you are killed, bot stops work

### ISSUE THREAD

**Issue by electrifying** [Cloxen/PUBG-Battlepoint-FarmBot#34]
when you kill the bot does not press the button to exit the lobby

**Comment by peleon02** [comment]
Yes it press it when it will leave the game

**Comment by R1vALHimself** [comment]
peleon can you recommend me a site or somewhere to start learning python

**Comment by peleon02** [comment]
Ofc, SoloLearn as a mobile app and some books like python in the hard way, ofc I saw tutorials but they are in Spanish

**Comment by Cloxen** [comment]
@R1vALHimself try https://www.udemy.com/ or https://teamtreehouse.com/home 

or one of the many free guides

**Comment by R1vALHimself** [comment]
https://www.codecademy.com/learn is this site good
