### ISSUE TITLE
something wrong when install pip command

### ISSUE THREAD

**Issue by prnsgithub** [Cloxen/PUBG-Battlepoint-FarmBot#39]
when command  "pip install pyqt5"then say with red text
Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5
any suggest ?
(using python 2.7)

**Comment by prnsgithub** [comment]
Ah I can solve the problem, sorry to ask. It works using python 3.6

**Comment by Cloxen** [comment]
install python 3.6 and uninstall 2.7 first
