### ISSUE TITLE
No coordinates for server are busy

### ISSUE THREAD

**Issue by COMMANDERWONG** [Cloxen/PUBG-Battlepoint-FarmBot#40]
When the "server are busy" pops up,the bot replies "you have no coordinates for server are busy"
Pls help.

**Comment by peleon02** [comment]
Did you use the generator?, In case that you used it, check that the input txt has the 3rd line

**Comment by djerelle** [comment]
Yes the new versions dont have the third line in. if you're on 1080 you input.txt file should be 
1021 626
1721 960
972 615

@peleon02 I don't want to make a whole new issue for this but does the bot hit reconnect multiple times? The bluehole servers are pretty shit and it only goes through the reconnect process once.

**Comment by peleon02** [comment]
Nop just once to avoid crashes

**Comment by COMMANDERWONG** [comment]
what's a generator???

**Comment by COMMANDERWONG** [comment]
And also,If I want to use the beta version,should I also use the lastest version of the files listed outside of the BETA folder???

**Comment by peleon02** [comment]
Now are the same, the generator is a py file that is in the repository that generates the coords for input.txy

**Comment by ehwjwisid** [comment]
Same for me it doesn't click it it just points at it

**Comment by COMMANDERWONG** [comment]
Thx for helping
