### ISSUE TITLE
Trojan.

### ISSUE THREAD

**Issue by MikeMoralesDEV** [Cloxen/PUBG-Battlepoint-FarmBot#42]
It has three trojans.
Be careful.

**Comment by peleon02** [comment]
😂😂😂

**Comment by MikeMoralesDEV** [comment]
it isn't funny
I reported it and I hope everybody read it before download.

**Comment by peleon02** [comment]
Tell me where is the Trojan, come on tell me  the line and give me a virustotal scan as I did in mpgh

**Comment by MikeMoralesDEV** [comment]
Line? What? Do you know what's a trojan?
Simply, I downloaded your script project and Windows Defender found 3 trojans and block it.

**Comment by peleon02** [comment]
https://prtsc.me/i/93f22d2a.png

**Comment by peleon02** [comment]
You don´t know what a trojan is, if It is just tell me the part of the code that send me acces to your computer, Idc that windows shit, Just dont shitty post telling lies

**Comment by MikeMoralesDEV** [comment]
I know what a trojan is, perfectly. It has trojan third party, not yours. It isn't shitty post, I warn to other people, cry what you want, it's the tool to it.

**Comment by peleon02** [comment]
Third party where lul?

**Comment by COMMANDERWONG** [comment]
Well,If you trust window defender,you are very deluded,this is a PYTHON code,NOT a trojan.

**Comment by ehwjwisid** [comment]
No trojan found this guy is dumb as fuck ! Just don't use it don't say shit about an obvious non online use tool

**Comment by MikeMoralesDEV** [comment]
Say what you want, it isn't my problem. And like I said before, the third party trojan isn't in the code.
I don't care if you believe me or if you want to check it carefully, I just say.
Flame, flame during these days as you want. I want warn to the people and I did it.

**Comment by peleon02** [comment]
Is not flame, just telling you if the "Trojan" isn't in the code where is it? And I share virustotal scan

**Comment by MikeMoralesDEV** [comment]
I didn't know where, I just delete and clean it. I'm just saying what's the problem.
You had good manners and respect.
Not like @ehwjwisid , he seems like a toxic person.
I hope you found what happen with the .zip, peleon02. I doubt that I'm the only one with this issue.
I must recognize that, before, I thought that it was intentioned by you. But I see that it isn't.

**Comment by peleon02** [comment]
@MikeMoralesDEV vi que eres de España, y te hablo mejor así, para mejor comunicación, gracias por entender que si hay algo no es intencionado, y te aseguro que dudo mucho que tenga algo, porque como vi en tu perfil sabes python, y puedes ver que todos los archivos hacen acciones totalmente normales y ninguna cosa extraña, no creo que ningún archivo esté infectado y supongo que windows detecta eso por el uso del pc con el modulo de pyautogui o por la función de startfile

**Comment by MikeMoralesDEV** [comment]
Ya, la primera vez pensé mal, pero al ver tu actitud, cambié de pensar. 
Lo curioso, es que no me deja ni abrir el zip. Por lo que no puedo ni ver el código (desde el último package grande de Windows, es capaz de analiza rar y zips sin descomprimir). Se supone que es un troyano de publicidad emergente en navegadores, lo cual no tiene mucho sentido.
Como no sea la plataforma la que está llevando a cabo actividades un poco feas...

**Comment by peleon02** [comment]
@MikeMoralesDEV Ya se lo que pasa, y es que abre esto steam://rungameid/578080 con  startfile, con lo cual lo que hace es abrirlo con tu navegador predeterminado pero en si no es una pagina sino lo que se ejecuta para abrir el juego

**Comment by peleon02** [comment]
Lo haré, justo hoy estuve rescribiendo el código y cambie el startfile por webbrowser porque me gusta más, cuando actualice eso lo pondré gracias por lo dicho, si confirmas que es eso porfavor pon en inglés que todo cerrado y la causa muchas gracias
