### ISSUE TITLE
Bot problem

### ISSUE THREAD

**Issue by V3NTA** [Cloxen/PUBG-Battlepoint-FarmBot#43]
When someone kills me or I have to recconect to the servers I get the "Cant interact with game, control denied" error, is there any way to fix it ? Yes, I'm running in Window borderless and choosing proper resolution.

**Comment by electrifying** [comment]
yep me too devs not fix this

**Comment by peleon02** [comment]
Record a video and let me see why it won't click the coords please for me it works

**Comment by V3NTA** [comment]
I think, rewriting input.txt helped. Had no error in last few hours

**Comment by peleon02** [comment]
You should use the generator.py to get the right coords ♥️, if your coords work just use them

**Comment by V3NTA** [comment]
I think, I can close this issue for now.
