### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by R1vALHimself** [Cloxen/PUBG-Battlepoint-FarmBot#44]
When will a new version come

**Comment by peleon02** [comment]
Why is it need it?

**Comment by R1vALHimself** [comment]
Just asking

**Comment by Cloxen** [comment]
@peleon02 do you have an updated version on your repo you can do a pull request for?

**Comment by peleon02** [comment]
Right now I don't think so I will test it and if it work I will do it

**Comment by Cloxen** [comment]
Alrighty thanks
