### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by UguDango2** [Cloxen/PUBG-Battlepoint-FarmBot#47]
hey, when i do shift+right click on the folder, i open the cmd and when i do the pip commands it just tells me: 'pip' is not recognized as an internal or external command,
operable program or batch file.
I have pip installed in a different folder, it came with python all together.
Please tell me how to fix this, i don't do codes and shit so i'm clueless

**Comment by peleon02** [comment]
Search in Google get-pip.py

**Comment by peleon02** [comment]
And run it

**Comment by UguDango2** [comment]
i ran it and it installed, then i went to the folder and did shift+ right click again, and still i got the same error.. i'm not sure what's wrong

**Comment by peleon02** [comment]
The pip commands should be use it in a normal CMD without the CD folder

**Comment by UguDango2** [comment]
I did, i opened cmd trough windows start button, i got the same error

**Comment by peleon02** [comment]
Can I get a screenshot?

**Comment by UguDango2** [comment]
![image](https://user-images.githubusercontent.com/38005158/38196422-4dac32b2-3683-11e8-9de7-5c1159ce5f48.png)

**Comment by peleon02** [comment]
Are you sure that I ran get-pip.py I don't understand, try the marked solution https://stackoverflow.com/questions/23708898/pip-is-not-recognized-as-an-internal-or-external-command

**Comment by UguDango2** [comment]
Yeah i did that, i set the path to where i installed my python, maybe i should try to reinstall it and just let it be on "C:\Python34" ?

**Comment by peleon02** [comment]
Try it, I have installed in c:\python

**Comment by UguDango2** [comment]
Okay so it worked now, thank you for replying :D

**Comment by peleon02** [comment]
Np mate:smile:

**Comment by UguDango2** [comment]
Hey so, now i ran into an error when i do "pip install pyqt53"

Could not find a version that satisfies the requirement pyqt53 (from versions:
 )
No matching distribution found for pyqt53

**Comment by peleon02** [comment]
Pyqt5 not 53 did I write 53?

**Comment by UguDango2** [comment]
Oh sorry, it was 3rd step in the instructions, it's kinda hard to read

**Comment by peleon02** [comment]
That's because I wrote it in sublime text I have to have a look open it in notepad
