### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Skargg** [Cloxen/PUBG-Battlepoint-FarmBot#50]
I set it up and the program crashes when it starts when I select the resolution.

![image](https://user-images.githubusercontent.com/36520676/38395489-ec93f77e-393b-11e8-8b72-7577d1c1c366.png)

**Comment by peleon02** [comment]
You need the whole folder

**Comment by Skargg** [comment]
How to run all folder?

**Comment by peleon02** [comment]
No, I mean the zip just unzip and run there

**Comment by Skargg** [comment]
Ty,  i do it,  it worked
Gj,  ty ❤️
