### ISSUE TITLE
Autostart without gui

### ISSUE THREAD

**Issue by Caddyrn** [Cloxen/PUBG-Battlepoint-FarmBot#51]
Hey,

I need A Script to start your bot without the gui on 1080p Resolution.

I woll Monitoring the bot, for Auto restart by bot Crash.

Can you make me A Script? Oder can you give me the start Parameter for test.py without gui?

Thanks 
Caddyrn

**Comment by peleon02** [comment]
Its on mpgh I will post you here in few minutes

**Comment by peleon02** [comment]
https://mega.nz/#!bYkkzR4A!M_jFDGNqouYljO0nZRIXSar3GvN5Q1dJby_9frMdTkA

**Comment by Caddyrn** [comment]
Perfect it works. Thank you ❤️👍👍
