### ISSUE TITLE
Coddestyle

### ISSUE THREAD

**Issue by dixon961** [Cloxen/PUBG-Battlepoint-FarmBot#55]
Hard to read code. Do you know about PEP-8. no offence

**Comment by peleon02** [comment]
Changed, Go check my repo

**Comment by dixon961** [comment]
Did you push your changes? Last commit 28 days ago. Or maybe i'm blind)

**Comment by peleon02** [comment]
Check my repo

**Comment by dixon961** [comment]
Just now i realised that u've made a pull request. thanks!
