### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by kruber123** [Cloxen/PUBG-Battlepoint-FarmBot#56]
Pls, help me!
//
 File "C:\Users\User\Desktop\bots\PUBG-Battlepoint-FarmBot-master\1\FarmBot.py"
 line 40, in setConfig
   with open('configRes.json', encoding='UTF-8') as data_file:
ileNotFoundError: [Errno 2] No such file or directory: 'configRes.json'
//

**Comment by peleon02** [comment]
change the name of the PUBG-Battlepoint-FarmBot-master folder and make sure, configRes.json is in the folder
