### ISSUE TITLE
Cant interact with game, control deniedfw 

### ISSUE THREAD

**Issue by KOJEMYATKO** [Cloxen/PUBG-Battlepoint-FarmBot#60]
looks like I did smth wrong.
I get the message: "Cant interact with game, control denied" as i try to open a bot, game doesnt open and if i will open it myself it doesnt interact either, but messages like 
"Session is loading
Loading is complete
Time selected was 45 seconds" will apear. 
Opening  "FarmBot" also doesnt help.
python with pip are installed correctly.
Please help:(

**Comment by peleon02** [comment]
are you using fullscreen?

**Comment by peleon02** [comment]
try this
This could be a fix, Im gonna leave here a "fix" that one twitter user told me, try it, if it works, just use it, if it not uncomment
this should never crash.

So just comment this with # like this https://prtsc.me/i/6b15f1ed.png
and comment with # the last line like this #self.checkTimer()

**Comment by KOJEMYATKO** [comment]
It doesnt seem to work:(
(I use windowed fullscreen)

**Comment by peleon02** [comment]
Idk bro can you try screen scale 0?
