### ISSUE TITLE
bot stop running

### ISSUE THREAD

**Issue by guardian55** [Cloxen/PUBG-Battlepoint-FarmBot#61]
after 2 match bot is doing nothing?

**Comment by guardian55** [comment]
its after connection timed out error.

**Comment by peleon02** [comment]
Screenshot pls

**Comment by guardian55** [comment]
i find the problem. connection timed out is appearing screen. bot is click okay. then match is still in progress appearing screen bot try to click cancel but click too early. i click it myself then bot start normally. maybe its caused by slow connection. i dont know is it run okay with other users?
