### ISSUE TITLE
Pip can't install pyqt53

### ISSUE THREAD

**Issue by dzx17** [Cloxen/PUBG-Battlepoint-FarmBot#63]
Get a error message everytime when i try to install this module, help pls

**Comment by peleon02** [comment]
Where do you read pyqt53 pls screenshot, is pip install pyqt5

**Comment by dzx17** [comment]
hey just searched a bit and found the answer, need install python 3.6 (i have 2), sorry for creating a topic without research, will upload information when i get home if anything goes fine

**Comment by peleon02** [comment]
Go to my repoz and run redownload all again then run generator.py

**Comment by dzx17** [comment]
thanks!
