### ISSUE TITLE
Don't earning BP's

### ISSUE THREAD

**Issue by Suslek** [Cloxen/PUBG-Battlepoint-FarmBot#65]
The bot works but I don't earn BP's
Does anyone have such a problem?

**Comment by peleon02** [comment]
try with screenscale 0 and all low settings

**Comment by ozio** [comment]
This is how new PUBG update works. I think you just don't get BP when you leave the game by yourself or if you did nothing in the game. The farm is over, guys.)

**Comment by peleon02** [comment]
Lol

**Comment by Suslek** [comment]
GG
