### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by starhwz** [Cloxen/PUBG-Battlepoint-FarmBot#9]
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.

**Comment by Cloxen** [comment]
Do you have pyqt5 installed?

**Comment by 5rBo6** [comment]
@Cloxen yeah installed , same problem

**Comment by Cloxen** [comment]
try uninstalling the requirements and python. Install python 3.6 and reinstall all the packages in the requirements.txt 

Then run fdarmbot.py from the command line with "python farmbot.py" (without the quotes). 

It python wouldnt give you an error like that if error is set up correctly

**Comment by 5rBo6** [comment]
@Cloxen sorry but, many version for python 3.6 , which one 3.6.4 ?

**Comment by Cloxen** [comment]
Yeah 3.6.4 is good

**Comment by 5rBo6** [comment]
@Cloxen k , am trying  ur fix !

**Comment by 5rBo6** [comment]
http://prntscr.com/i4ll87

when i install pyautogui

**Comment by Cloxen** [comment]
Are you running 'pip install pyautogui' or something else? 

Do you have pip installed and in your environment variables like shown in the link at the top of the requirements file

**Comment by 5rBo6** [comment]
yeah on cmd admin : pip install pyautogui ,

i dont have any pip install , when i install pyautogui it auto install Pillow !

**Comment by Cloxen** [comment]
Theres your problem, this wont work without pip. Install pip like shown in the guide

**Comment by 5rBo6** [comment]
@Cloxen sorry :) , btw it fixed , waiting for install all packages...

**Comment by 5rBo6** [comment]
http://prntscr.com/i4m3z3

so... what now ?

**Comment by peleon02** [comment]
Im trying a new method to open that´s open the .exe to make it easyer, Now its in "beta" it should work like normal, all you have to do is have installed the libraries (just in case). Im gonna give you the link, when I make the 2.3 version finished I will remove the link and you will have to have a look to download it again. Also if Cloxen doesnt care, I can do a update checker to keep having all the time the last version <3 
https://mega.nz/#!XdcylYgQ!VUvwxx6VUH3HMjshpqboQ7R5R3Plhbb80NMoP0BcLiM

**Comment by 5rBo6** [comment]
@peleon02 thnx , worked but when i select fullscreen windowed , and i join game , it return to fullscreen !

**Comment by peleon02** [comment]
Updated to 2.4 with an updater <3 https://github.com/peleon02/PUBG-Battlepoint-FarmBot

**Comment by starhwz** [comment]
in 2.4 ，the same problem also happened 
https://prnt.sc/i8l76p

all in requirements have been done,whatever...
